name: Build and Push to ECR

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          ECR_REPO: ${{ secrets.ECR_REPO }}
        run: |
         TAG=${{ github.sha }}
          docker build --no-cache -t twitter-server server 
          docker tag twitter-server:latest $ECR_REPO:$TAG
          docker tag twitter-server:latest $ECR_REPO:latest
          docker push $ECR_REPO:$TAG
          docker push $ECR_REPO:latest

      - name: SSH into EC2 and pull new image
        run: |
          TAG=${{ github.sha }}
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            echo "${{ secrets.ENV_FILE }}" > .env
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
              docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}
            docker pull ${{ secrets.ECR_REPO }}:$TAG
            docker stop twitter-server || true
            docker rm twitter-server || true
            docker run -d --name twitter-server --env-file .env -p 3000:3000 ${{ secrets.ECR_REPO }}:$TAG
            rm .env
            docker image prune -f
            echo "Cleanup done."

          EOF
